# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MODIS_data_collector
                                 A QGIS plugin
 MODIS_data_collector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-19
        copyright            : (C) 2023 by Alexey Kolesnikov
        email                : 1@1.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MODIS_data_collector class from file MODIS_data_collector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MODIS_data_collector import MODIS_data_collector
    return MODIS_data_collector(iface)
