# -*- coding: utf-8 -*-
"""
/***************************************************************************
 poly2datalens
                                 A QGIS plugin
 poly2datalens
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-26
        copyright            : (C) 2023 by Alexey Kolesnikov
        email                : a@a.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load poly2datalens class from file poly2datalens.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .poly2datalens import poly2datalens
    return poly2datalens(iface)
